// This file is auto-generated by TanStack Router CLI

import { Route as RootRoute } from "./routes/_root";
import { Route as AppRoute } from "./routes/_app";
import { Route as AppIndexRoute } from "./routes/_app.index";
import { Route as AppProfileRoute } from "./routes/_app.profile";
import { Route as AppEditProfileRoute } from "./routes/_app.edit-profile";
import { Route as AppMySuggestionsRoute } from "./routes/_app.my-suggestions";
import { Route as AppMyWatchlistRoute } from "./routes/_app.my-watchlist";
import { Route as AppSuggestedToMeRoute } from "./routes/_app.suggested-to-me";
import { Route as AppNotificationsRoute } from "./routes/_app.notifications";
import { Route as AppExploreRoute } from "./routes/_app.explore";
import { Route as AppExploreTrendingRoute } from "./routes/_app.explore.trending";
import { Route as AppExploreRecommendedRoute } from "./routes/_app.explore.recommended";
import { Route as AppExploreFriendActivityRoute } from "./routes/_app.explore.friend-activity";
import { Route as AppContentIdRoute } from "./routes/_app.content.$id";
import { Route as AppMoviesIdRoute } from "./routes/_app.movies.$id";
import { Route as AppSeriesIdRoute } from "./routes/_app.series.$id";
import { Route as AppBooksIdRoute } from "./routes/_app.books.$id";
import { Route as AppMusicIdRoute } from "./routes/_app.music.$id";
import { Route as AuthRoute } from "./routes/_auth";
import { Route as AuthLoginRoute } from "./routes/_auth.login";
import { Route as AuthSignupRoute } from "./routes/_auth.signup";

export const routeTree = RootRoute.addChildren([
  AppRoute.addChildren([
    AppIndexRoute,
    AppProfileRoute,
    AppEditProfileRoute,
    AppMySuggestionsRoute,
    AppMyWatchlistRoute,
    AppSuggestedToMeRoute,
    AppNotificationsRoute,
    AppExploreRoute.addChildren([
      AppExploreTrendingRoute,
      AppExploreRecommendedRoute,
      AppExploreFriendActivityRoute,
    ]),
    AppContentIdRoute,
    AppMoviesIdRoute,
    AppSeriesIdRoute,
    AppBooksIdRoute,
    AppMusicIdRoute,
  ]),
  AuthRoute.addChildren([AuthLoginRoute, AuthSignupRoute]),
]);
